/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package crudDisciplina;

import disciplina.Disciplina;
import disciplina.GerenciarDisciplina;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Pedro Kravetz
 */
public class DisciplinaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProfessorDialog
     *
     * @param parent
     * @param modal
     */
    public DisciplinaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        errorLB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        dadosDisciplinaLB = new javax.swing.JLabel();
        nomeLB = new javax.swing.JLabel();
        codigoLB = new javax.swing.JLabel();
        blocoLB = new javax.swing.JLabel();
        salaLB = new javax.swing.JLabel();
        cargaHorariaLB = new javax.swing.JLabel();
        ementaLB = new javax.swing.JLabel();
        bibliografiaLB = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        cancelarBT = new javax.swing.JButton();
        blocoTF = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bibliografiaTA = new javax.swing.JTextArea();
        salaTF = new javax.swing.JFormattedTextField();
        cargaHorariaTF = new javax.swing.JFormattedTextField();
        codigoTF = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ementaTF = new javax.swing.JTextPane();
        errorLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        dadosDisciplinaLB.setText("Dados da Disciplina");

        nomeLB.setText("Nome: ");

        codigoLB.setText("Código: ");

        blocoLB.setText("Bloco: ");

        salaLB.setText("Sala: ");

        cargaHorariaLB.setText("Carga Horária: ");

        ementaLB.setText("Ementa: ");

        bibliografiaLB.setText("Bibliografia: ");

        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        cancelarBT.setText("Cancelar");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        try {
            blocoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bibliografiaTA.setColumns(20);
        bibliografiaTA.setRows(5);
        jScrollPane2.setViewportView(bibliografiaTA);

        try {
            salaTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cargaHorariaTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            codigoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jScrollPane3.setViewportView(ementaTF);

        errorLB.setForeground(java.awt.Color.red);
        errorLB.setText("Dados Incorretos");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(salvarBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarBT))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ementaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bibliografiaLB, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nomeLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigoLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blocoLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(salaLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cargaHorariaLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(codigoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blocoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(salaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(cargaHorariaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addComponent(errorLB))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(dadosDisciplinaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelarBT, salvarBT});

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {blocoTF, cargaHorariaTF, jScrollPane2, nomeTF, salaTF});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosDisciplinaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLB)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLB)
                    .addComponent(codigoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blocoLB)
                    .addComponent(blocoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaLB)
                    .addComponent(salaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargaHorariaLB)
                    .addComponent(cargaHorariaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(ementaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(bibliografiaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(errorLB)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBT)
                    .addComponent(cancelarBT))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        limparTextos();
    }//GEN-LAST:event_formWindowClosed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        if (validarForm()) {
            errorLB.setVisible(false);
            
            disciplina.setNome(nomeTF.getText().trim());
            disciplina.setCodigo(codigoTF.getText().trim());
            disciplina.setBibliografia(bibliografiaTA.getText().trim());
            disciplina.setBloco(blocoTF.getText().trim().charAt(0));
            disciplina.setCargaHoraria(Integer.parseInt(cargaHorariaTF.getText().trim()));
            disciplina.setEmenta(ementaTF.getText().trim());
            disciplina.setSala(Integer.parseInt(salaTF.getText().trim()));
            if (disciplina.getId() == 0) {
                gerDisciplina.create(disciplina);
            } else {
                gerDisciplina.update(disciplina);
            }
            
            dispose();
        } else {
            errorLB.setVisible(true);
        }
    }//GEN-LAST:event_salvarBTActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        resize(new Dimension());
    }//GEN-LAST:event_formWindowActivated
    
    private void limparTextos() {
        nomeTF.setText("");
        codigoTF.setText("");
        blocoTF.setText("");
        salaTF.setText("");
        cargaHorariaTF.setText("");
        ementaTF.setText("");
        bibliografiaTA.setText("");
    }
    
    private boolean validarForm() {
        boolean isValido = true;
        
        if (nomeTF.getText().trim().equals("")) {
            isValido = false;
            nomeLB.setForeground(Color.red);
        } else {
            nomeLB.setForeground(Color.black);
        }
        
        if (codigoTF.getText().trim().length() != 5) {
            isValido = false;
            codigoLB.setForeground(Color.red);
        } else {
            codigoLB.setForeground(Color.black);
        }
        
        if (blocoTF.getText().trim().equals("")) {
            isValido = false;
            blocoLB.setForeground(Color.red);
        } else {
            blocoLB.setForeground(Color.black);
        }
        
        if (salaTF.getText().trim().length() != 3) {
            isValido = false;
            salaLB.setForeground(Color.red);
        } else {
            try {
                Integer.parseInt(salaTF.getText().trim());
                salaLB.setForeground(Color.black);
            } catch (Exception e) {
                isValido = false;
                salaLB.setForeground(Color.red);
            }
        }
        if (cargaHorariaTF.getText().trim().equals("")) {
            isValido = false;
            cargaHorariaLB.setForeground(Color.red);
        } else {
            try {
                Integer.parseInt(cargaHorariaTF.getText().trim());
                cargaHorariaLB.setForeground(Color.black);
            } catch (Exception e) {
                isValido = false;
                cargaHorariaLB.setForeground(Color.red);
            }
        }
        
        if (ementaTF.getText().trim().equals("")) {
            isValido = false;
            ementaLB.setForeground(Color.red);
        } else {
            ementaLB.setForeground(Color.black);
        }
        
        if (bibliografiaTA.getText().trim().equals("")) {
            isValido = false;
            bibliografiaLB.setForeground(Color.red);
        } else {
            bibliografiaLB.setForeground(Color.black);
        }
        return isValido;
    }
    
    public Disciplina getDisciplina() {
        return disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    
    public void setGerDisciplina(GerenciarDisciplina gerDisciplina) {
        this.gerDisciplina = gerDisciplina;
    }
    
    public void objectToForm() {
        nomeTF.setText(disciplina.getNome());
        codigoTF.setText(disciplina.getCodigo());
        blocoTF.setText(String.valueOf(disciplina.getBloco()));
        salaTF.setText(String.valueOf(disciplina.getSala()));
        cargaHorariaTF.setText(String.valueOf(disciplina.getCargaHoraria()));
        ementaTF.setText(disciplina.getEmenta());
        bibliografiaTA.setText(disciplina.getBibliografia());
    }
    
    private GerenciarDisciplina gerDisciplina;
    private Disciplina disciplina;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bibliografiaLB;
    private javax.swing.JTextArea bibliografiaTA;
    private javax.swing.JLabel blocoLB;
    private javax.swing.JFormattedTextField blocoTF;
    private javax.swing.JButton cancelarBT;
    private javax.swing.JLabel cargaHorariaLB;
    private javax.swing.JFormattedTextField cargaHorariaTF;
    private javax.swing.JLabel codigoLB;
    private javax.swing.JFormattedTextField codigoTF;
    private javax.swing.JLabel dadosDisciplinaLB;
    private javax.swing.JLabel ementaLB;
    private javax.swing.JTextPane ementaTF;
    private javax.swing.JLabel errorLB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nomeLB;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel salaLB;
    private javax.swing.JFormattedTextField salaTF;
    private javax.swing.JButton salvarBT;
    // End of variables declaration//GEN-END:variables

}
