/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package crudAluno;

import aluno.Aluno;
import aluno.GerenciarAluno;
import endereco.Endereco;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import pessoa.Sexo;

/**
 *
 * @author Pedro Kravetz
 */
public class AlunoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProfessorDialog
     *
     * @param parent
     * @param modal
     */
    public AlunoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        errorLB.setVisible(false);
        sdf = new SimpleDateFormat("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        dadosAnoLB = new javax.swing.JLabel();
        nomeLB = new javax.swing.JLabel();
        emailLB = new javax.swing.JLabel();
        dataNascimentoLB = new javax.swing.JLabel();
        sexoLB = new javax.swing.JLabel();
        cpfLB = new javax.swing.JLabel();
        rgLB = new javax.swing.JLabel();
        raLB = new javax.swing.JLabel();
        periodoLB = new javax.swing.JLabel();
        anoLB = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        nomeTF = new javax.swing.JTextField();
        raTF = new javax.swing.JTextField();
        periodoTF = new javax.swing.JTextField();
        masculinoRBT = new javax.swing.JRadioButton();
        femininoRBT = new javax.swing.JRadioButton();
        salvarBT = new javax.swing.JButton();
        cancelarBT = new javax.swing.JButton();
        cepLB = new javax.swing.JLabel();
        ruaLB = new javax.swing.JLabel();
        bairroLB = new javax.swing.JLabel();
        numeroLB = new javax.swing.JLabel();
        complementoLB = new javax.swing.JLabel();
        ruaTF = new javax.swing.JTextField();
        bairroTF = new javax.swing.JTextField();
        numeroTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        complementoTF = new javax.swing.JTextArea();
        errorLB = new javax.swing.JLabel();
        dataNascimentoTF = new javax.swing.JFormattedTextField();
        cpfTF = new javax.swing.JFormattedTextField();
        rgTF = new javax.swing.JFormattedTextField();
        cepTF = new javax.swing.JFormattedTextField();
        anoTF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        dadosAnoLB.setText("Dados do Aluno");

        nomeLB.setText("Nome: ");

        emailLB.setText("Email: ");

        dataNascimentoLB.setText("Data de Nascimento: ");

        sexoLB.setText("Sexo: ");

        cpfLB.setText("CPF: ");

        rgLB.setText("RG: ");

        raLB.setText("RA: ");

        periodoLB.setText("Período:");

        anoLB.setText("Ano: ");

        buttonGroup1.add(masculinoRBT);
        masculinoRBT.setText("Masculino");

        buttonGroup1.add(femininoRBT);
        femininoRBT.setText("Feminino");

        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        cancelarBT.setText("Cancelar");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        cepLB.setText("CEP:");

        ruaLB.setText("Rua: ");

        bairroLB.setText("Bairro: ");

        numeroLB.setText("Número: ");

        complementoLB.setText("Complemento");

        complementoTF.setColumns(20);
        complementoTF.setRows(5);
        jScrollPane1.setViewportView(complementoTF);

        errorLB.setForeground(java.awt.Color.red);
        errorLB.setText("Dados incorretos");

        try {
            dataNascimentoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cpfTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            rgTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cepTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            anoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosAnoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataNascimentoLB, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(emailLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sexoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cpfLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rgLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(raLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataNascimentoTF)
                                    .addComponent(emailTF)
                                    .addComponent(nomeTF)
                                    .addComponent(cpfTF)
                                    .addComponent(rgTF)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(masculinoRBT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(femininoRBT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(raTF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(complementoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cepLB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(periodoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(periodoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(cepTF, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(anoTF)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(ruaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruaTF))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(bairroLB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroTF))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(numeroLB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTF))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(salvarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarBT)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelarBT, salvarBT});

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anoLB, bairroLB, cepLB, complementoLB, numeroLB, ruaLB});

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cepTF, periodoTF, raTF});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosAnoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLB)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLB)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoLB)
                    .addComponent(dataNascimentoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLB)
                    .addComponent(masculinoRBT)
                    .addComponent(femininoRBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLB)
                    .addComponent(cpfTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLB)
                    .addComponent(rgTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raLB)
                    .addComponent(raTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodoLB)
                    .addComponent(periodoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoLB)
                    .addComponent(anoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLB)
                    .addComponent(cepTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaLB)
                    .addComponent(ruaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroLB)
                    .addComponent(bairroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLB)
                    .addComponent(numeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(complementoLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(errorLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarBT)
                            .addComponent(cancelarBT))
                        .addGap(27, 27, 27))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        limparTextos();
    }//GEN-LAST:event_formWindowClosed

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        if (validarForm()) {
            errorLB.setVisible(false);

            aluno.setNome(nomeTF.getText().trim());

            try {
                Date dataNasc = sdf.parse(dataNascimentoTF.getText().trim());
                aluno.setDataNascimento(dataNasc);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data inválida");
                return;
            }

            aluno.setCpf(cpfTF.getText().trim());
            aluno.setRg(rgTF.getText().trim());
            aluno.setEmail(emailTF.getText().trim());
            aluno.setRa(Integer.parseInt(raTF.getText().trim()));
            aluno.setPeriodo(periodoTF.getText().trim());
            aluno.setAno(anoTF.getText().trim());

            if (masculinoRBT.isSelected()) {
                aluno.setSexo(Sexo.MASCULINO);
            } else {
                aluno.setSexo(Sexo.FEMININO);
            }

            if (aluno.getId() == 0) {
                gerAluno.create(aluno);
            } else {
                gerAluno.update(aluno);
            }

            dispose();
        } else {
            errorLB.setVisible(true);
        }
    }//GEN-LAST:event_salvarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlunoDialog dialog = new AlunoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
        this.endereco = aluno.getEndereco();
    }

    private void limparTextos() {
        buttonGroup1.clearSelection();
        nomeTF.setText("");
        cpfTF.setText("");
        rgTF.setText("");
        raTF.setText("");
        periodoTF.setText("");
        anoTF.setText("");
        dataNascimentoTF.setText("");
        emailTF.setText("");
        cepTF.setText("");
        bairroTF.setText("");
        ruaTF.setText("");
        numeroTF.setText("");
        complementoTF.setText("");
    }

    private boolean validarForm() {
        boolean isValido = true;
        if (raTF.getText().trim().equals("")) {
            isValido = false;
            raLB.setForeground(Color.red);
        } else {
            raLB.setForeground(Color.black);
        }

        if (periodoTF.getText().trim().equals("")) {
            isValido = false;
            periodoLB.setForeground(Color.red);
        } else {
            periodoLB.setForeground(Color.black);
        }

        if (anoTF.getText().trim().length() != 4) {
            isValido = false;
            anoLB.setForeground(Color.red);
        } else {
            anoLB.setForeground(Color.black);
        }

        if (cepTF.getText().trim().length() != 9) {
            isValido = false;
            cepLB.setForeground(Color.red);
        } else {
            cepLB.setForeground(Color.black);
        }

        if (bairroTF.getText().trim().equals("")) {
            isValido = false;
            bairroLB.setForeground(Color.red);
        } else {
            bairroLB.setForeground(Color.black);
        }

        if (ruaTF.getText().trim().equals("")) {
            isValido = false;
            ruaLB.setForeground(Color.red);
        } else {
            ruaLB.setForeground(Color.black);
        }

        if (numeroTF.getText().trim().equals("")) {
            isValido = false;
            numeroLB.setForeground(Color.red);
        } else {
            numeroLB.setForeground(Color.black);
        }

        if (nomeTF.getText().trim().equals("")) {
            isValido = false;
            nomeLB.setForeground(Color.red);
        } else {
            nomeLB.setForeground(Color.black);
        }

        if (dataNascimentoTF.getText().trim().length() != 10) {
            isValido = false;
            dataNascimentoLB.setForeground(Color.red);
        } else {
            dataNascimentoLB.setForeground(Color.black);
        }

        if (cpfTF.getText().trim().length() != 14) {
            isValido = false;
            cpfLB.setForeground(Color.red);
        } else {
            cpfLB.setForeground(Color.black);
        }

        if (rgTF.getText().trim().length() != 12) {
            isValido = false;
            rgLB.setForeground(Color.red);
        } else {
            rgLB.setForeground(Color.black);
        }

        if (emailTF.getText().trim().equals("")) {
            isValido = false;
            emailLB.setForeground(Color.red);
        } else {
            emailLB.setForeground(Color.black);
        }

        if (!(masculinoRBT.isSelected() || femininoRBT.isSelected())) {
            isValido = false;
            sexoLB.setForeground(Color.red);
        } else {
            sexoLB.setForeground(Color.black);
        }
        errorLB.setVisible(true);
        return isValido;
    }

    public void setGerenciarAluno(GerenciarAluno gerAluno) {
        this.gerAluno = gerAluno;
    }

    public void objectToForm() {
        nomeTF.setText(aluno.getNome());
        cpfTF.setText(aluno.getCpf());
        rgTF.setText(aluno.getRg());
        emailTF.setText(aluno.getEmail());
        dataNascimentoTF.setText(sdf.format(aluno.getDataNascimento()));
        if (aluno.getSexo() == Sexo.MASCULINO) {
            masculinoRBT.setSelected(true);
        } else {
            femininoRBT.setSelected(true);
        }
    }

    private SimpleDateFormat sdf;
    private Aluno aluno;
    private Calendar cal;
    private GerenciarAluno gerAluno;
    private Endereco endereco;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLB;
    private javax.swing.JFormattedTextField anoTF;
    private javax.swing.JLabel bairroLB;
    private javax.swing.JTextField bairroTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarBT;
    private javax.swing.JLabel cepLB;
    private javax.swing.JFormattedTextField cepTF;
    private javax.swing.JLabel complementoLB;
    private javax.swing.JTextArea complementoTF;
    private javax.swing.JLabel cpfLB;
    private javax.swing.JFormattedTextField cpfTF;
    private javax.swing.JLabel dadosAnoLB;
    private javax.swing.JLabel dataNascimentoLB;
    private javax.swing.JFormattedTextField dataNascimentoTF;
    private javax.swing.JLabel emailLB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel errorLB;
    private javax.swing.JRadioButton femininoRBT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton masculinoRBT;
    private javax.swing.JLabel nomeLB;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel numeroLB;
    private javax.swing.JTextField numeroTF;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel periodoLB;
    private javax.swing.JTextField periodoTF;
    private javax.swing.JLabel raLB;
    private javax.swing.JTextField raTF;
    private javax.swing.JLabel rgLB;
    private javax.swing.JFormattedTextField rgTF;
    private javax.swing.JLabel ruaLB;
    private javax.swing.JTextField ruaTF;
    private javax.swing.JButton salvarBT;
    private javax.swing.JLabel sexoLB;
    // End of variables declaration//GEN-END:variables
}
